# fly.toml app configuration file generated for ths-delivery on 2023-05-25T22:53:06-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ths-delivery"
primary_region = "mia"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
